### ISSUE TITLE
Дизайн блока авторизации (войти, зарегистрироваться, выйти)

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#12]
1. Создать хедер с дизайном кнопки "Войти" в правой части хедера.

> Реф с timepad:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/8cf32bde-a456-4118-95a1-0f30cd9634d9)

2. Создать хедер с дизайном "пустой аватарки" и выпадашки с выбором "Выйти"

> Почти реализованная версия (убрать строку "Профиль"):
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/60d708fe-8a3d-4f40-95bf-4c1bb5e44aeb)

**Comment by VladaHaustova** [comment]
Хедер с дизайном кнопки "Войти" https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3600-1089&mode=design
Хедер с дизайном "пустой аватарки" и выпадашки с выбором "Выйти" https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3600-1090&mode=design

**Comment by VolumeCore** [comment]
Ок

**Comment by nikitonya** [comment]
Утверждённый вариант дизайна:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/d9ac4146-185a-4cb3-8aa8-583efc665721)
