### ISSUE TITLE
Вёрстка блока авторизации

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#13]
Задача заключается в 
1. Вёрстке шапки сайта с элементами «войти» для неавторизованного пользователя 
2. Вёрстке шапки сайта с элементами "заглушка аватарки пользователя" и выпадашкой "выйти".
При наведении на заглушку должно выводиться ФИ ползователя в формате "Имя Фамилия"

Дизайн находиться в figma in page "[User Story #10](https://github.com/IT-Prospects/business-calendar/issues/10)"
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/8e5726fc-768f-4871-b6a0-328a8d181dcf)

Если есть вопросы - в ЛС @nikitonya

**Comment by nikitonya** [comment]
При открытии сайта пользователь становится сразу авторизованным, без всякого имени при наведении (фото 1).

![Image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/794c3490-0777-47f4-b41c-ede401dfa786)

Нужно чтобы при открытии сайта блок был в состоянии с кнопкой "Войти".

Комментарий от @Victorina13: "Это баг, ибо там одно поле для двух форм и валидация тоже. Исправим"

**Comment by VolumeCore** [comment]
Сейчас там захардкожено значение, можешь проверить. Когда свяжем с бэком, будет реально имя отображаться

**Comment by nikitonya** [comment]
1. Значок не по центру
2. Необходимо сделать его больше как и в дизайне
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/2872b553-a60a-4be0-876a-4b08581c4be4)

**Comment by nikitonya** [comment]
Принятый вариант вёрстки:

![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/5b57d595-0752-4e2f-b30e-97545e9db2a4)
