### ISSUE TITLE
Дизайн поп-апа "Вход"

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#14]
Всё отлично в уже реализованной версии:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/847e5084-a679-49dd-864b-95ffb013bdd7)

**Comment by nikitonya** [comment]
1. **Задача не может быть выполнена без DoD: https://github.com/IT-Prospects/business-calendar/wiki/Definitions-of-Done.**
Попрошу ещё раз внимательно ознакомиться.
2. **Также необходимо выполнять сначала задачи из приоритетной User Stroy (Urgent).** 
Здесь возможно исключение, так как эти таски уже выполнены, но в любом случае DoD для них не выполнился.

Перевожу задачу в In Progress.

**Comment by VladaHaustova** [comment]
Дизайн поп-апа "Вход" в user story #10 https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3580-1391&mode=design

**Comment by VolumeCore** [comment]
Ок
