### ISSUE TITLE
Вёрстка поп-апа "Вход"

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#15]
Поп-ап войти должен возникать после нажатия на кнопку "Войти" в хедере.

Вёрстка должна соответсвовать дизайну, который находиться в figma на page "[User Story #10](https://github.com/IT-Prospects/business-calendar/issues/10)"

1. **Поле электронная почта**

> Длина поля электронная почта - Имя пользователя должно быть до 31 символа включительно.

2. **Поле "пароль"**
> Длина поля "пароля" - от 8 знаков до 40 знаков. Валидацию используй стандартную от ангуляра.

3. **Крестик**

> Сделай такое же Hover отображение как и в "Я пойду".
> ![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/820fdcc4-e94d-4178-9d9e-821c98652c5c)

4. **Сообщения при валидации**  

> Описание внутри задачи https://github.com/IT-Prospects/business-calendar-frontend/issues/84

Вопросы - @nikitonya

**Comment by nikitonya** [comment]
При введении валидных значений кнопка не загорается (фото 1). Запущено всё локально.

![Image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/7bd42b51-b341-4f81-b011-b03f1ebda043)

Комментарий от @Victorina13: "Это баг, ибо там одно поле для двух форм и валидация тоже. Исправим". 

Жду правок!

**Comment by nikitonya** [comment]
Принятый вариант вёрстки:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/73e710fa-c319-4c52-a253-7d89e046279b)
