### ISSUE TITLE
Дизайн поп-апа "Регистрация"

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#16]
Всё отлично в реализованной версии, только изменить текст "Подтвердить пароль" на "Подтверждение пароля"
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/a68ea4a5-42de-4db4-9f22-e43fbe612c5b)

**Comment by VladaHaustova** [comment]
Дизайн поп-апа "Регистрация" в user story #10 https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3580-1410&mode=design

**Comment by VolumeCore** [comment]
Ок

**Comment by nikitonya** [comment]
Утверждённый дизайн:

![Image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/f300f89f-4c0e-434c-956c-902a42bc8a5a)
