### ISSUE TITLE
Вёрстка поп-апа "Зарегистрироваться"

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#17]
Поп-ап "Зарегистрироваться" должен возникать после нажатия на кнопку "Зарегистрируйтесь" внутри поп-апа "Вход".

**Поле ОБЯЗАТЕЛЬНО ДЛЯ ЗАПОЛНЕНИЯ**
При незаполнении любого поля подсвечивать поле красным цветом и выводить текст  "Это поле обязательно для заполнения".
Пример:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/7b7a8186-2b26-4303-9ed0-5327446119b4)

**Поле электронная почта**
Длина поля электронная почта - Имя пользователя должно быть до 31 символа включительно.

**Поле "пароль"**
Длина поля "пароля" - от 8 знаков до 40 знаков. Валидацию используй стандартную от ангуляра.

**Валидация (сообщения об ошибке)**
Фамилия - "Введите фамилию"
Имя - "Введите имя"
Для почты - "Введите в формате example@gmail.com"
Для пароля - "Введите пароль".
Для подтверждения - "Введите пароль"
Также поле должно посвечиваться красным как тут:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/0f585390-af3a-4297-9cc8-eb1730bd683d)

**Крестик**
Сделать такое же Hover отображение как и в "Я пойду".

Вёрстка должна соответствовать дизайну, который находиться в figma на page "https://github.com/IT-Prospects/business-calendar/issues/10"
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/e426187c-281e-4f90-97ec-54345380628f)

Вопросы - @nikitonya

**Comment by nikitonya** [comment]
Принятый вариант вёрстки:

![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/d42903c1-c321-4dc3-a5f5-5e76aeed62ca)
