### ISSUE TITLE
Дизайн страницы "Подробности мероприятия"

### ISSUE THREAD

**Issue by nikitonya** [IT-Prospects/business-calendar-frontend#22]
Эта страница должна открываться после нажатия на клавишу "Детали" на карточке мероприятия.
Страница должна в себе содержать:
1. Хедер (std)
2. Основное тело
3. Футер (std)

Внутри основного тела странички должна лежать следующая информация:
1. Фотография мероприятия
2. Название мероприятия
3. Дата, время, продолжительность в текстовом виде рядом с иконкой часов.
4. Адрес здания, город рядом с иконкой геолокации.
5. Подробное описание мероприятия

**Comment by nikitonya** [comment]
### User Story звучит так: 
[Как гость сайта, я хочу посмотреть подробности о мероприятии, чтобы решить, насколько мероприятие мне интересно.](https://github.com/IT-Prospects/business-calendar/issues/6)

### Уточнения по поводу правок в дизайне главного экрана к этой User Story:
1. Поля поиска быть не должно.
2. Блока регистрации и авторизации быть не должно.
3. Фразу "бесплатно" убрать.
4. Блок заполнения данных для записи на мероприятие убрать.
5. Кнопку "Я пойду" убрать.
6. Футер переделать под тот, который сделан на основной странице.

**Comment by iryzzz** [comment]
https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3138-1760&mode=design

**Comment by nikitonya** [comment]
Необходимо убрать из шапки блоки "войти" и "зарегистироваться", переношу задачу в "In progress".

**Comment by VolumeCore** [comment]
Дизайн ок

**Comment by nikitonya** [comment]
Нужно убрать кнопку "Присоединиться". Для закрытия этой Story эта кнопка не нужна.
@iryzzz
