### ISSUE TITLE
Дизайн страницы "Подробности мероприятия" с кнопкой

### ISSUE THREAD

**Issue by nikitonya** [IT-Prospects/business-calendar-frontend#26]
Дополнить к дизайну страницы "подробности мероприятия" кнопку "Я пойду"

**Comment by nikitonya** [comment]
Дополнить к дизайну страницы "подробности мероприятия" кнопку "Я пойду"

**Comment by VladaHaustova** [comment]
1. Добавлена кнопка "Я пойду" на карточке мероприятия в main https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3346-1343&mode=design
2. Добавлена кнопка "Я пойду" на карточке мероприятия в user story #7 https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3476-1580&mode=design&t=Xm5Dh2wbjpdiheX4-11

**Comment by VolumeCore** [comment]
Всё ок
