### ISSUE TITLE
Дизайн поп-апа "С вами свяжется организатор"

### ISSUE THREAD

**Issue by nikitonya** [IT-Prospects/business-calendar-frontend#27]
Этот поп-ап должен всплывать после заполнения данных для записи на мероприятие в поп-апе "Я пойду" и нажатии на кнопку "Отправить"

**Comment by nikitonya** [comment]
Этот поп-ап должен всплывать после заполнения данных для записи на мероприятие в поп-апе "Я пойду" и нажатии на кнопку "Отправить"

**Comment by iryzzz** [comment]
https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=0-1&mode=design на холсте "popups"

**Comment by nikitonya** [comment]
nice.
