### ISSUE TITLE
Дизайн попапа "Эта функциональность ещё недоступна"

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#34]
Чтобы не скрывать элементы на фронте, для которых ещё нет реализации, нужно выводить попап "Эта функциональность ещё недоступна"

**Comment by iryzzz** [comment]
https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=0-1&mode=design
