### ISSUE TITLE
Дизайн главного экрана

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#4]
В рамках данной задачи должен быть создан дизайн:
- [x] шапки сайта 
- [x] компоновки основных элементов
- [x] маленького вида карточки мероприятия
- [x] карточки мероприятия для анонса
- [x] дизайн выпадашки с месяцами
- [x] дизайн "слайдер дат"
- [x] футера сайта
- [x] дизайн сообщения "ничего не найдено" (при отсутсвии мероприятий за конкретную дату)
- [x] карточка анонса dummy мероприятия

**Comment by prafdin** [comment]
На Владу

**Comment by nikitonya** [comment]
### User Story звучит так: 
Как гость сайта, я хочу просматривать список мероприятий, чтобы выбрать то, что мне интересно согласно дате мероприятия.

### Уточнения по поводу правок в дизайне главного экрана к этой User Story:
1. Блока регистрации и авторизации быть не должно (а на будущее в нём нужно поменять местами "войти" и "зарегистрироваться").
2. Блока поиска быть не должно.
3. Поля фильтра быть не должно.
4.  Фразу "бесплатно" убираем отовсюду.

**Comment by VladaHaustova** [comment]
https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=0-1&mode=design

**Comment by VolumeCore** [comment]
Всё норм, дизайн устраивает
