### ISSUE TITLE
Дизайн кнопки "Я пойду" на карточке мероприятия

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#43]
На карточке мероприятия должна быть кнопка "Я пойду". Сделать варианты с активной кнопкой и неактивной.

**Comment by VladaHaustova** [comment]
1. Варианты кнопок в UI kit (Normal - кнопка по умолч., Hover - наведение мыши, Pressed - клик мышью, Disabled - кнопка недоступна) https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=2778-78&mode=design
2. Добавлена кнопка "Я пойду" на карточке мероприятия в main

**Comment by VladaHaustova** [comment]
3. Добавлена кнопка "Я пойду" на карточке мероприятия в user story #7 https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3476-1580&mode=design&t=Xm5Dh2wbjpdiheX4-11

**Comment by VolumeCore** [comment]
Всё ок

**Comment by nikitonya** [comment]
1. Нужно создать страницу в фигме User Story #7 и туда закинуть эту страницу. Из main не удаляй этот Temp.
![Image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/af5d9dcd-f680-43b0-a63b-bcfb08031756)
2. То, что ты сделала, это другая задача - https://github.com/IT-Prospects/business-calendar-frontend/issues/26.
В рамках этой должна быть кнопка "Я пойду" на главной странице на карточке мероприятия рядом с кнопкой "Детали."

Перевожу таску в In Progress.

**Comment by VladaHaustova** [comment]
Добавлена кнопка "Я пойду" на главной странице на карточке мероприятия в двух вариациях на выбор https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=0-1&mode=design

**Comment by nikitonya** [comment]
Изменения дизайна кнопки "Я пойду" на карточке мероприятия после DEMO 2 спринта 07.11.2023:

1. Кнопка "Детали" должна быть слева
2. Кнопка "Я пойду" справа
3. Фон обоих кнопок светлый
4. Обводка фиолетовая
5. Текст внутри фиолетовый
6. Сделать вариант неактивной кнопки в сером цвете только для одной кнопки - кнопки "Я пойду"
7. Также можно добавить какую-то заливку цветом при наведении на кнопку. По твоему усмотрению!

Примерно как это должно выглядеть:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/b2cd1213-ecc5-4125-9a0b-de02e84ddd9a)

Stroke = 1 давай оставим, посмотрел сейчас вёрстку на данный момент в dev, мне так нравится:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/7d6eedd0-d35b-403a-8c9c-67c03bf6b262)

**Comment by VladaHaustova** [comment]
Изменения дизайна кнопки с учетом замечаний https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=3484-1540&mode=design

**Comment by nikitonya** [comment]
Всё отлично! 
Утверждённый дизайн:

![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/96fcf24a-d5f6-4886-a493-1b98c97259a3)
