### ISSUE TITLE
Верстка кнопки "Я пойду" на карточке мероприятия

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#44]
Нужно сверстать карточку https://github.com/IT-Prospects/business-calendar-frontend/issues/43

**Comment by nikitonya** [comment]
Всё отлично, утверждённый вариант вёрстки:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/44d65797-c7fe-4d82-ab7c-489eb241c4df)
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/c59b7643-a180-498c-8bd2-3e995ea38ca6)
