### ISSUE TITLE
Доработка дизайна поп-апа "Я пойду"

### ISSUE THREAD

**Issue by nikitonya** [IT-Prospects/business-calendar-frontend#62]
Внести изменения в дизайн поп-апа я пойду:

1. Изменить текст в заголовке поп-апа с "Ваши данные" на "Регистрация на мероприятие"
2. Убрать поле "ФИО"
3. Создать поле "Фамилия"
4. Создать поле "Имя"

Итого должно быть 4 поля:

1. Фамилия
2. Имя
3. Электронная почта
4. Номер телефона

**Comment by iryzzz** [comment]
https://www.figma.com/file/3ye6liAjbV6aASyk7ZiIf7/project?type=design&node-id=0-1&mode=design холст "popups'

**Comment by nikitonya** [comment]
nice.

Утверждённый вариант дизайна:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/e9522179-5c2a-4287-abce-40ca4efff8ee)
