### ISSUE TITLE
Использовать 0.2.0 версию API в frontend

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#70]
После решения тикета https://github.com/IT-Prospects/business-calendar-backend/issues/22 изменилось DTO 
эвента, нужно обновить фронтенд согласно новым изменениям. 

Теперь эвент присылает не image name, а image url

API https://github.com/IT-Prospects/business-calendar-backend/blob/main/BusinessCalendar/swagger.json
Для визуализации https://editor.swagger.io/

**Comment by nikitonya** [comment]
Проверено @prafdin. Закрываю таску.
