### ISSUE TITLE
Синхронизировать календарь и выпадашку с месяцем

### ISSUE THREAD

**Issue by nikitonya** [IT-Prospects/business-calendar-frontend#79]
При нажатии даты из месяца, не выбранном в выпадашке, месяц в выпадашке должен меняться

**Comment by prafdin** [comment]
worked

**Comment by nikitonya** [comment]
Принятый вариант:
![синхронизация календаря с выпадашкой](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/edac8d86-ac6a-4670-8ed0-5ebca952f971)
