### ISSUE TITLE
Листать по 2 дня по кнопке в календаре

### ISSUE THREAD

**Issue by nikitonya** [IT-Prospects/business-calendar-frontend#81]
При нажатии на стрелку в слайдере необходимо сделать пролистывание сразу 2 дат, а не одной.

**Comment by prafdin** [comment]
Worked

**Comment by nikitonya** [comment]
Принятый вариант:
![2 дня](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/204bbd53-181e-4df0-b74d-55ab4d7d1e99)
