### ISSUE TITLE
Сделать иконку для вкладки

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-frontend#98]
Нужен дизайн иконки для сайта 

Имеется ввиду вот эта иконка:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/73230804/a6abd96c-1c17-4504-9429-2d14d0741e41)

**Comment by VladaHaustova** [comment]
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/92472083/ca414881-6efb-4760-8f19-025f32ee76c3)

**Comment by VladaHaustova** [comment]
Браузер с темой по умолчанию:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/92472083/3de22373-efca-42d5-841a-0f17c5619c5f)
С темной темой: 
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/92472083/ac497059-6ff6-4bd6-9c51-8e622cd2c842)
Результат гугл запроса:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/92472083/728d3e83-bb9d-41e1-af49-6e2c2b08ef7c)
Мобильная версия гугл запроса:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/92472083/afd3fc2f-d916-4fd0-aa85-70671697499b)
Результат запроса в сафари:
![image](https://github.com/IT-Prospects/business-calendar-frontend/assets/92472083/0caaff8c-e189-403d-b475-7ab09fae6a82)

Нужно распаковать архив в рут веб-сайта, в нем будет файл favicon.ico
Если сайт http://www.example.com, то должен быть доступ к файлу с именем http://www.example.com/favicon.ico.
Архив:
[favicon_package_v0.16.zip](https://github.com/IT-Prospects/business-calendar-frontend/files/13678611/favicon_package_v0.16.zip)

**Comment by nikitonya** [comment]
Всё великолепно, принято
